function [status] = DAQmxWriteDigitalU32(taskHandle, numSampsPerChan,...
    bAutoStart, timeout, bDataLayout, writeArray, sampsPerChanWritten)

[status, ~, ~] = daq.ni.NIDAQmx.DAQmxWriteDigitalU32(taskHandle, int32(numSampsPerChan),...
    uint32(bAutoStart), timeout, uint32(bDataLayout), uint32(writeArray), int32(sampsPerChanWritten),uint32(0));