function [status, readArray] = DAQmxReadDigitalU32(taskHandle, numSampsPerChan,...
    timeout, fillMode, readArray, arraySizeInSamps, sampsPerChanRead)

[status, readArray, ~, ~] = daq.ni.NIDAQmx.DAQmxReadDigitalU32(taskHandle, int32(numSampsPerChan),...
    timeout, uint32(fillMode), uint32(readArray), uint32(arraySizeInSamps), int32(sampsPerChanRead), uint32(0));