function [status, readArray, sampsPerChanRead]=DAQmxReadCounterU32(taskHandle, numSampsPerChan,...
    timeout, readArray, arraySizeInSamps, sampsPerChanRead )

[status,readArray, sampsPerChanRead, reserved]=daq.ni.NIDAQmx.DAQmxReadCounterU32(taskHandle, int32(numSampsPerChan), ...
    timeout, uint32(readArray), uint32(arraySizeInSamps), sampsPerChanRead,uint32(0));