function [status] = DAQmxConnectTerms(strSourceTerminal,...
    strDestinationTerminal, signalModifiers);


[status] = calllib('mynidaqmx','DAQmxConnectTerms',strSourceTerminal,...
    strDestinationTerminal, signalModifiers);