function [status] = DAQmxCreateDIChan(taskHandle, strLines,...
    strNameToAssignToLines, lineGrouping);

[status] = calllib('mynidaqmx','DAQmxCreateDIChan',taskHandle, strLines, ...
    strNameToAssignToLines, lineGrouping);